### ISSUE TITLE
Bump to Spark 1.3.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/spark-example-project#1]

**Comment by bigsnarfdude** [comment]
Pull request pending for this issue. EMR Test https://gist.github.com/bigsnarfdude/92154d84ce222e118bac

**Comment by alexanderdean** [comment]
I'm going to try taking this to Spark 1.3.1...

**Comment by alexanderdean** [comment]
Changed to 1.3.0 for compatibility with https://github.com/awslabs/emr-bootstrap-actions/tree/master/spark
